# A request message is sent from an action client to an action server initiating a new goal
Trajectory trajectory
---
# A result message is sent from an action server to an action client when a goal is done.
bool success
ActionResultFlag action_result_flag
string info
---
# Feedback messages are periodically sent from an action server to an action client with updates about a goal.
string status
RobotStatus robot_status
float64 progress